# Specify the API URL of slack incomming webhook.
API_URL: 'THIS_IS_API_URI'

# If you wouldn't like to send a messaage to slack and only to check on it, specify 'true'.
DEBUG_MODE: false

# The log is outputed here. It includes stack trace and debug above.
LOG_FILE: './trace.log'
